# Generated by Django 3.1.7 on 2021-04-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_auto_20210401_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisor',
            name='user',
            field=models.CharField(max_length=255, verbose_name='Пользователь'),
        ),
    ]
